### ISSUE TITLE
Definere data som skal være med ved henting av sykmelding

### ISSUE THREAD

**Issue by ghost** [navikt/sykmeldinger#11]
Definere hvilke data som mangler ved henting av Sykmelding fra api.

Eksempel:
- Når sykemelding ble bekreftet (statuspanel)
- Når sykemelding ble avvist (statuspanel)

Kan vi minste antall kall som gjøres?
For eksempel: kan nærmeste leder, og erUtenforVentetid sendes sammen med sykmelding?

**Comment by sebdak** [comment]
[https://github.com/navikt/syfosmregister/blob/207a5775a3fff4b9a59a9758af0fc5766dc19488/src/main/kotlin/no/nav/syfo/aksessering/api/dataSykmeldingDTO.kt]

Her er forsløpig format på sykmelding. Har begynt å lage klasse for det. Må nok ha litt flere felt, som feks prognose og utdypende opplysninger.
