### ISSUE TITLE
Vurder om åpning av <Utvidbar /> skal animeres

### ISSUE THREAD

**Issue by ghost** [navikt/sykmeldinger#20]
I tidligere løsning animeres åpningen av innholdet i \<Utvidbar />. Vurder om dette bedrer brukeropplevelsen og bør innføres i \<Utvidbar />

**Comment by jhnav** [comment]
Problem: Innholdet animeres basert på maxHeight. Maxheight settes når Utvidbar åpnes.

Dersom det er flere utvidbar i hverandre, oppdateres ikke maxHeight for den ytre Utvidbar når den indre Utvidbar utvides.

En testet løsning er å håndtere høyden med useState i container for begge Utvidbar. Når en av de ekspanderes, oppdateres høyden, og høyden for begge legges sammen. Da får man animert ved åpning både på ytre og indre Utvidbar.

For å fullføre denne oppgaven må det lages en løsning der Utvidbar-komponenten håndterer setting av høyde selv.

**Comment by sebdak** [comment]
Kjell-Arne har snakket om dette problemet tidligere, ville tatt en prat med han om hvordan han løste det
