### ISSUE TITLE
Oversikt over mock-sykmeldinger

### ISSUE THREAD

**Issue by jhnav** [navikt/sykmeldinger#50]
Det finnes ingen enkel måte å komme seg til en sykmelding fra localhost:3000.

Det bør lages et endepunkt i mocken som henter ut sykmeldinger, og en mock-side i sykmeldinger som lister de tilgjengelige sykmeldingene med en lenke til sykmeldingen.

**Comment by sebdak** [comment]
Se om du er fornøyd med #51.
