### ISSUE TITLE
Revurdere mockdata lokalt i app

### ISSUE THREAD

**Issue by sebdak** [navikt/sykmeldinger#52]
Synes det er litt "hassle" å måtte spinne opp to apper for development, og sørge for at de kjører på riktig port. Det systemet her funker bra for sømløs brukertest mellom appene (nytt-sykefravaer og sykmeldinger), men er ikke så veldig utviklervennlig. Vedlikehold av sykefravaer-mock blir potensielt også en utfordring for fremtidige utviklere. 

Tror dog det blir vanskelig å unngå å bruke sykefravaer-mock ved utvikling av nytt-sykefravaer hvis man ønsker å kunne gå gjennom hele brukerhistorien. Den må nok forbli for dette.

Angående problemet med å da måtte sørge for at dataen er lik i alle appene, så tror jeg ikke det vil endre seg så mye på sikt.

**Forslag:**
Endringer i `index.tsx`.
```
if (process.env.REACT_APP_DEMO) {
    ReactDOM.render(<DemoWrapper />, document.getElementById('root'));
} else {
    if (process.env.NODE_ENV === 'development') {
        require('./mock');
    }
    ReactDOM.render(<App />, document.getElementById('root'));
}
```
`process.env.NODE_ENV` settes automatisk til `development` (av webpack) når man kjører lokalt, og settes til `production` når det bygges.
Scripts vil da:
- `npm start`: lokal mock-data i dev og live-data i Q og prod.
- `npm run start-demo`: laster DemoWrapper

**Comment by jhnav** [comment]
Enig.

**Comment by johenie** [comment]
Gjøres som del av refaktoreringsjobben
